---
- name: Install remote facts
  hosts: fedora
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
   - name: Create the remote directory
     file:
      state: directory
      recurse: yes
      path: "{{ remote_dir }}"
   - name: Install the new facts
     copy:
      src: "{{ facts_file }}"
      dest: "{{ remote_dir }}"
   - name: Install Apache and starts the service
     yum:
      name: "{{ ansible_facts['ansible_local']['custom']['general']['package'] }}"
      state: latest
