---
- name: Hello Amine I m playone !!
  hosts: all
  vars:
    services_to_be_up:
     - mariadb
     - sshd
     - firewalld     
    mariadb_packages:
     - mariadb-server
     - python3-PyMySQL
    supported_os:
     - Fedora
     - RedHat
     
  tasks:
    - name : Mariadb packages are installed or not??
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ mariadb_packages }}"
      notify:
       - set db pwd
    - name: Start MariaDB service
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ services_to_be_up }}"
      when:  ansible_distribution in supported_os 
    - name : modify http 
      template:
        src: /tmp/http
        dest: /etc/httpd/conf/httpd.conf
      notify:
        - restarti apachi
    - name : modify my
      template:
        src: /tmp/myy
        dest: /etc/my.conf
      notify:
        - restarti maria

  handlers:
   - name: restarti apachi
     service:
       name: httpd
       state: restarted
   - name: restarti maria
     service:
       name: mariadb
       state: restarted
   - name: set db pwd
     mysql_user:
      name: root
      password: redhat


